Adding PT-BR Translation
RadicalxChange/quadratic-voting pull request #13
Opened 2021-05-18 21:48 UTC by blckjzz

### What has changed?
I've worked on the translation of the inner pages of the QV Quadratic Voting app.
### What should I pay attention when reviewing this PR?
The translation didn't change the time and date formats. Which needs some attention, since Brazilians are used to "dd/MM/YYYY" format instead of  "MM/dd/YYYY" format.
### Is this PR dangerous?
No.

2021-05-19 18:02 UTC, alexrandaccio requested changes
Thanks for doing these translations! I think we should give users language options in the footer, so that both languages can coexist in the codebase. Create a top-level language prop that determines which text is loaded.

I'll try to do this later, and if we don't end up having time to get it done, we'll just create a separate branch for the Portuguese text and deploy that branch when needed.

2021-05-19 19:13 UTC, blckjzz commented
@alexrandaccio that's awesome. I'm no expert on github, but what you said about the branch makes sense. I've tried to figure how to suggest this my translated branch to a new branch into your repo, which I failed to do. It seems that the branch should be already in your repository, and at the giving time it was not (not your fault). If you create a pt-br branch, I should be able to change this PR to it and would not mess with you master.

2021-05-19 19:22 UTC, alexrandaccio commented
oh that's no problem, don't worry about the github stuff. I already took care of it!

2021-06-14 17:08 UTC, alexrandaccio approved these changes

2021-06-14 17:09 UTC, merged